import { test } from "node:test";
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { postgresSQL, databaseURL } from "../database.js";

const ROOT = fileURLToPath(new URL("../", import.meta.url));

test("Postgres translation preserves placeholders inside strings and API aliases", () => {
  const sql = postgresSQL("SELECT '?' AS literal, author_name AS by, user_id AS authorId FROM replies WHERE complaint_id = ?");
  assert.equal(sql, "SELECT '?' AS \"literal\", author_name AS \"by\", user_id AS \"authorId\" FROM replies WHERE complaint_id = $1");
  assert.match(postgresSQL("CREATE TABLE users (id INTEGER PRIMARY KEY)"), /GENERATED BY DEFAULT AS IDENTITY/);
});

test("Vercel rejects missing hosted storage instead of using disposable SQLite", () => {
  const result = spawnSync(process.execPath, ["--input-type=module", "-e", 'await import("./api/index.js")'], {
    cwd: ROOT, env: { ...process.env, DATABASE_URL: "", POSTGRES_URL: "", SUPABASE_DB_URL: "", VERCEL: "1" }, encoding: "utf8", timeout: 5000
  });
  assert.equal(result.status, 1);
  assert.match(result.stderr, /Set DATABASE_URL/);
});

test("serverless entry exports Express without opening a listener", () => {
  const dir = mkdtempSync(path.join(tmpdir(), "zerostars-entry-"));
  try {
    const result = spawnSync(process.execPath, ["--no-warnings", "--input-type=module", "-e", 'const {default: app} = await import("./api/index.js"); if (typeof app !== "function") process.exit(1);'], {
      cwd: ROOT, env: { ...process.env, DATABASE_URL: "", POSTGRES_URL: "", SUPABASE_DB_URL: "", VERCEL: "", DATA_DIR: dir, DB_PATH: "", SEED_FORCE: "" }, encoding: "utf8", timeout: 5000
    });
    assert.equal(result.error, undefined);
    assert.equal(result.status, 0, result.stderr);
    assert.doesNotMatch(result.stdout, /running on port/);
  } finally { rmSync(dir, { recursive: true, force: true }); }
});

test("Supabase integration connection names are supported with explicit URL precedence", () => {
  assert.equal(databaseURL({ POSTGRES_URL: "pooler-url" }), "pooler-url");
  assert.equal(databaseURL({ SUPABASE_DB_URL: "supabase-url" }), "supabase-url");
  assert.equal(databaseURL({ DATABASE_URL: "explicit", POSTGRES_URL: "pooler-url" }), "explicit");
  assert.equal(databaseURL({ NEXT_PUBLIC_SUPABASE_URL: "https://project.supabase.co", NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "public-key" }), "");
});
