// The same async query interface supports local SQLite and hosted Postgres.
import pg from "pg";

export function databaseURL(env = process.env) {
  return env.DATABASE_URL || env.POSTGRES_URL || env.SUPABASE_DB_URL || "";
}
export const isPostgres = Boolean(databaseURL());
if (process.env.VERCEL && !isPostgres) {
  throw new Error("Set DATABASE_URL (or POSTGRES_URL / SUPABASE_DB_URL) to the Supabase pooler connection string before deploying.");
}

export function postgresSQL(sql) {
  let index = 0;
  // Convert placeholders only outside SQL strings, identifiers, and comments.
  sql = sql.replace(/'(?:''|[^'])*'|"(?:""|[^"])*"|--[^\n]*|\?/g,
    token => token === "?" ? `$${++index}` : token);
  sql = sql.replace(/datetime\('now'\)/g,
    "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')");
  // PostgreSQL otherwise folds camelCase API aliases to lowercase.
  sql = sql.replace(/\bAS ([a-zA-Z][a-zA-Z0-9_]*)/g, 'AS "$1"');
  sql = sql.replace(/\bid INTEGER PRIMARY KEY\b/g, "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
  if (/INSERT OR IGNORE INTO/i.test(sql)) {
    sql = sql.replace(/INSERT OR IGNORE INTO/i, "INSERT INTO").trim() + " ON CONFLICT DO NOTHING";
  }
  return sql;
}

export function createPostgresDatabase(pool) {
  return {
    // Schema migrations already contain native Postgres SQL.
    async exec(sql) { await pool.query(sql); },
    prepare(sql) {
      const query = (params, returning = false) => {
        let text = postgresSQL(sql);
        if (returning && /^\s*INSERT INTO/i.test(text)) {
          text += /^\s*INSERT INTO sessions\b/i.test(text) ? " RETURNING token" : " RETURNING id";
        }
        return pool.query(text, params);
      };
      return {
        async get(...params) { return (await query(params)).rows[0]; },
        async all(...params) { return (await query(params)).rows; },
        async run(...params) {
          const result = await query(params, true);
          return { lastInsertRowid: result.rows[0]?.id, changes: result.rowCount };
        }
      };
    },
    async close() { await pool.end(); }
  };
}

export async function openDatabase(sqlitePath, connectionString = databaseURL()) {
  if (!connectionString) {
    const { DatabaseSync } = await import("node:sqlite");
    const sqlite = new DatabaseSync(sqlitePath);
    sqlite.exec("PRAGMA journal_mode = WAL; PRAGMA foreign_keys = ON;");
    return sqlite;
  }
  const url = new URL(connectionString);
  const local = ["localhost", "127.0.0.1", "[::1]"].includes(url.hostname);
  // Keep TLS certificate verification enabled. URL sslmode options must not
  // override it; SUPABASE_CA_CERT can supply the project's trusted PEM CA.
  for (const key of ["sslmode", "sslcert", "sslkey", "sslrootcert"]) url.searchParams.delete(key);
  const pool = new pg.Pool({
    connectionString: url.toString(),
    max: 3,
    idleTimeoutMillis: 10000,
    connectionTimeoutMillis: 10000,
    allowExitOnIdle: true,
    ssl: local ? false : {
      rejectUnauthorized: true,
      ...(process.env.SUPABASE_CA_CERT ? { ca: process.env.SUPABASE_CA_CERT } : {})
    },
    types: { getTypeParser(oid, format) {
      return [20, 1700].includes(oid) ? Number : pg.types.getTypeParser(oid, format);
    } }
  });
  // Do not print connection errors, which can contain connection metadata.
  pool.on("error", () => console.error("An idle database connection failed."));
  return createPostgresDatabase(pool);
}
